name: muller_package
description: "A new Flutter package project."
version: 0.0.1
author: Victor Muller <victormuller050@gmail.com>

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  keyboard_avoider: ^0.2.0
  lottie: ^3.1.2
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
